### ISSUE TITLE
PAT is not needed because `kubernetes` repo is public

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/code-jam-management#21]
https://github.com/python-discord/code-jam-management/blob/c142f98dcdeadf73ac7785facb275b35eac285b6/.github/workflows/build.yaml#L77-L84

The comment is incorrect. The https://github.com/python-discord/kubernetes repo is already public, and the PAT is not needed and should be removed and deleted.

**Comment by ChrisLovering** [comment]
This is correct. It's used in quite a few places, none of them are required.

https://sourcegraph.com/search?q=context:global+repo:python-discord/*+secrets.REPO_TOKEN&patternType=standard

**Comment by shenanigansd** [comment]
Closed in favor of python-discord/kubernetes#140
